---

- name: Download OpenJDK 17 RI tarball
  get_url:
    url: https://download.java.net/openjdk/jdk17.0.0.1/ri/openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
    dest: /opt/openjdk-17_linux-x64_bin.tar.gz
    mode: '0644'
  become: yes

- name: Create /opt/java-17 directory
  file:
    path: /opt/java-17
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Extract OpenJDK 17 tarball
  unarchive:
    src: /opt/openjdk-17_linux-x64_bin.tar.gz
    dest: /opt/java-17
    extra_opts: [--strip-components=1]
    remote_src: yes
    creates: /opt/java-17/bin/java  # This makes the task idempotent

- name: Set JAVA_HOME and PATH in /etc/profile
  blockinfile:
    path: /etc/profile
    block: |
        export JAVA_HOME=/opt/java-17
        export PATH=$PATH:$JAVA_HOME/bin
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Java"

- name: Source profile for current session
  shell: source /etc/profile

- name: Create tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Download and extract Tomcat directly
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.108/bin/apache-tomcat-9.0.108.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: Fix ownership and permissions for Tomcat scripts
  file:
    path: /opt/tomcat
    owner: ec2-user
    group: ec2-user
    recurse: yes
  become: yes

- name: Make Tomcat scripts executable
  file:
    path: "{{ item }}"
    mode: '0755'
    owner: ec2-user
    group: ec2-user
  loop:
    - /opt/tomcat/bin/startup.sh
    - /opt/tomcat/bin/shutdown.sh
    - /opt/tomcat/bin/catalina.sh
  become: yes

- name: Create Tomcat systemd service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  notify:
    - reload systemd
    - restart tomcat

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes
    daemon_reload: true

- name: Wait for Tomcat on port 8080
  wait_for:
    host: 127.0.0.1
    port: 8080
    delay: 5
    timeout: 30

- name: Clean up downloaded archive
  file:
    path: /tmp/apache-tomcat-9.0.108.tar.gz
    state: absent
